num = 234

try:
     print(int(num) + 1)

except Exception as e :
    print("An error ocured")

else:
    print("Sucessfully executed")

finally:
    print("Its a finally clause")  



